### ISSUE TITLE
Better Chrome Driver Initialization

### ISSUE THREAD

**Issue by bhaskar-29** [DSC-NITA/HacktoberFest2020#28]
Hi @WinterSoldier13 
In the automation script regarding google meet, you used
![image](https://user-images.githubusercontent.com/71055334/95066601-3c7b6600-0720-11eb-9cc8-0f578cb84293.png)

I would suggest trying webdriver manager for Chrome driver initilization. I have seen many times that even after adding the executable path, the code throws an error and does not detect the path. Also, sometimes the issue of chromium version hampers the execution. 

So, I request you to let me add the desired code.

**Comment by iu-sh** [comment]
Okay, @bhaskar-29 go forward, I am assigning this issue to you.
