### ISSUE TITLE
Speech to Text using Python

### ISSUE THREAD

**Issue by reddymahendra52** [DSC-NITA/HacktoberFest2020#35]
* I can create a simple speech to text python program which is easy and anyone can do it
* I will also create a markdown on how to install the required modules  and implement in simple steps

**Comment by reddymahendra52** [comment]
Can assign this task to me??

**Comment by deepraj1729** [comment]
@reddymahendra52 Go for It and create `PR` having these criteria:-

1. All the `scripts` and `files` should be inside the `Automation-Scripts/` folder
2. Create the `README.md` about how to run the script
3. `requirements.txt` regarding the libraries required

**Comment by iu-sh** [comment]
Issue resolved with PR #37
